/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : flexPWM1.c
**     Project     : test_gpio
**     Processor   : MPC5744P_257
**     Component   : flexpwm
**     Version     : Component S32_SDK_C55, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-07-04, 14:00, # CodeGen: 13
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file flexPWM1.c
** @version 01.00
*/         
/*!
**  @addtogroup flexPWM1_module flexPWM1 module documentation
**  @{
*/         

/* MODULE flexPWM1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

#include "flexPWM1.h"

/*! flexPWM1 configuration structure */
const flexpwm_input_capture_config_t flexPWM1_flexpwm_input_capture_config_t0 = {
  .watermark = 0U,
  .inputSelect = FLEXPWM_RAW_PWM_INPUT,
  .edgeSelect0 = FLEXPWM_CAPTURE_EDGE_DISABLED,
  .edgeSelect1 = FLEXPWM_CAPTURE_EDGE_DISABLED,
  .oneShot = FLEXPWM_CAPTURE_FREE_RUNNIG,
  .edgeCompareVal = 0U,
  .edgeCntEn = FLEXPWM_CAPTURE_EDGE_CNT_DISABLED,
};

flexpwm_module_setup_t flexPWM1_flexpwm_module_setup_t0 = {
  .cntrInitSel = InitSrcLocalSync,
  .clkSrc = ClkSrcPwmPeriphClk,
  .clockFreq = 1000000U,
  .prescaler = PwmDividedBy1,
  .chnlPairOper = FlexPwmComplementary,
  .complementarySourceSel = FlexPwmComplementarySource23,
  .reloadLogic = FlexPwmReloadPwmHalfCycle,
  .reloadSource = FLEXPWM_LOCAL_RELOAD_SIGNAL,
  .reloadFreq = PwmLoadEvery1Oportunity,
  .forceTrig = ForceOutputLocalForce,
};

flexpwm_module_signal_setup_t flexPWM1_flexpwm_module_signal_setup_t0 = {
  .pwmPeriod = 1000U,
  .flexpwmType = FlexPwmEdgeAligned,
  .pwmAPulseWidth = 0U,
  .pwmBPulseWidth = 0U,
  .pwmAShift = 0U,
  .pwmBShift = 0U,
  .pwmAOuten = true,
  .pwmBOuten = true,
  .pwmXOuten = true,
  .pwmAPolarity = false,
  .pwmBPolarity = false,
  .pwmXPolarity = false,
  .pwmAFaultDisableMask = 0U,
  .pwmAfaultState = FLEXPWM_OUTPUT_STATE_LOGIC_0,
  .pwmBFaultDisableMask = 0U,
  .pwmBfaultState = FLEXPWM_OUTPUT_STATE_LOGIC_0,
  .pwmXFaultDisableMask = 0U,
  .pwmXfaultState = FLEXPWM_OUTPUT_STATE_LOGIC_0,
};

const flexpwm_fault_protection_config_t flexPWM1_flexpwm_fault_protection_config_t0 = {
  .filterPeriod = 0U,
  .filterCount = 0U,
  .glitchStretchEnable = false,
  .faultLevelMask = 0U,
  .autoFaultClearMask = 0U,
  .failSafeModeMask = 0U,
  .fullCycleMask = 0U,
};


/* END flexPWM1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

